### ISSUE TITLE
Change dark mode button 

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/Gallery#17]
hey there,

This is a good first issue. Solve it soon and create a pull request for the hacktoberfest 2022

**Comment by najeebkp** [comment]
Hi @thekavikumar  please assign me this!

**Comment by kishaangopi** [comment]
I would like to work on this issue. can u assign this issue to me?

**Comment by janvikumariii** [comment]
If I could work on this issue, I would appreciate it.

**Comment by thekavikumar** [comment]
Sure

**Comment by thekavikumar** [comment]
Try adding some new icon for dark mode
