### ISSUE TITLE
Improving frame of image

### ISSUE THREAD

**Issue by sangmesh04** [thekavikumar/Gallery#23]
When I upload image, if image contains black colour then delete icon is not visible. So, I can be improved by proper styling.

![image](https://user-images.githubusercontent.com/78370367/193411564-f4473414-de4d-492b-b0be-e016432255bd.png)

**Comment by sangmesh04** [comment]
I can work on this. Can you assign this task to me?

**Comment by thekavikumar** [comment]
Yup!

**Comment by thekavikumar** [comment]
Are you gonna add the feature bro?

**Comment by sangmesh04** [comment]
Yes, I worked on this feature and created a pull request.
