### ISSUE TITLE
Add some small and awesome features

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/Gallery#27]
Hey there,

You can add some small and nice looking and useful features to this project.
Thank you

**Comment by Rohitsingh385** [comment]
can you assign me the task

**Comment by thekavikumar** [comment]
Yeah sure

**Comment by thekavikumar** [comment]
@Rohitsingh385 are you working on this dude?

**Comment by Rohitsingh385** [comment]
Yes i am sorry i got a lil busy I'll update you tomorrow 10 am 😅sorry bro kinda busy cus of festival

**Comment by thekavikumar** [comment]
No problem bro. I was just confirming it.
