### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/Gallery#29]
Hey there,

Make the website responsive and create a pull request.

**Comment by asamaiya00** [comment]
Hi @thekavikumar, may I work on this? Please assign it to me

**Comment by thekavikumar** [comment]
Yeah sure!

**Comment by thekavikumar** [comment]
@asamaiya00 Are you working on this issue dude?

**Comment by asamaiya00** [comment]
Yes, almost completed. will raise PR @thekavikumar

**Comment by thekavikumar** [comment]
okay bro! grt
