### ISSUE TITLE
Any good features are welcomed! 

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/Gallery#42]
Hey there,

I welcome you all to contribute to my project even if your contribution is small.
Thank you

**Comment by piyush362** [comment]
put some logo

**Comment by thekavikumar** [comment]
where do u wanna put?

**Comment by piyush362** [comment]
Like my gallery logo, and some others

**Comment by thekavikumar** [comment]
okay, go ahead

**Comment by JamesKirawan** [comment]
how about we can do drag image instead of click?

**Comment by thekavikumar** [comment]
Oh!..try it

**Comment by thekavikumar** [comment]
I'm closing this issue, if any updates pls do open new issue
