### ISSUE TITLE
Funtionality to Delete the uploaded image

### ISSUE THREAD

**Issue by prateek-1606** [thekavikumar/Gallery#44]
Hi @thekavikumar , if you want i can add a feature to delete the uploaded image from the gallery.
Thanks

**Comment by thekavikumar** [comment]
Hey @prateek-1606 , It is already added do check out the website https://gallery-37066.web.app/
If you like to change the UI design of it, you can proceed with that.
For now I'm closing this issue.

**Comment by prateek-1606** [comment]
@thekavikumar i can't see any option to delete/remove uploaded image in the dashboard. 
![My-Gallery](https://user-images.githubusercontent.com/70057143/193584769-e54b6076-1feb-435a-81f1-b35f6e2701ec.png)

**Comment by thekavikumar** [comment]
Oops bro it is not visible due to its color.
Please switch to light mode.
