### ISSUE TITLE
Improve the Dark Mode

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/Gallery#55]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cleverhare** [comment]
Please assign it to me I am interested

**Comment by thekavikumar** [comment]
Yeah sure

**Comment by cleverhare** [comment]
Okay Thanks

**Comment by thekavikumar** [comment]
@cleverhare are you working on this issue?

**Comment by cleverhare** [comment]
Yes I have been working on it gonna be generating a PR soon

**Comment by thekavikumar** [comment]
Grt
