### ISSUE TITLE
Changing styling and designing of the page

### ISSUE THREAD

**Issue by biswajit150803** [thekavikumar/Gallery#57]
I want to make the page a bit more attractive and change the css styling

**Comment by thekavikumar** [comment]
Okay, do it!

**Comment by thekavikumar** [comment]
Is this for hacktoberfest?

**Comment by thekavikumar** [comment]
Make sure you also make it responsive

**Comment by biswajit150803** [comment]
Ok

**Comment by biswajit150803** [comment]
So plz assign it to me.

**Comment by thekavikumar** [comment]
I've assigned it to you! 
Happy contributing 💖
