### ISSUE TITLE
Avatar displays "p" if there is no profile picture regardless of the user's name

### ISSUE THREAD

**Issue by tklg** [thekavikumar/Gallery#58]
**Describe the bug**
If Google prevents the users avatar image from loading, Avatar component only shows "p" (from "profile pic")
![image](https://user-images.githubusercontent.com/1696813/193825568-88a92d68-5750-4a00-9b70-0e9de1dbd4d1.png)

**To Reproduce**
I dont know how or why google sometimes returns a 403 for the profile picture url,
Can reproduce it manually by blocking the picture url with devtools

**Expected behavior**
The avatar should display the user's initial(s) if the image is not available

**Comment by thekavikumar** [comment]
I think it not needed becoz sometimes on localhost firebase blocks the profile image, but in production build it works good
