### ISSUE TITLE
Improve the Dark theme

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/Gallery#62]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Candy505** [comment]
@thekavikumar I would like to undertake this and work to improve the dark theme, so that the background is dark enough but the text is easily readable! I quite like the light/dark mode button, nice!

**Comment by thekavikumar** [comment]
@Candy505 Hi, I appreciate that you came forward!
Thanks. I'll assign this to you.

**Comment by thekavikumar** [comment]
@Candy505 bro whats the progress

**Comment by Candy505** [comment]
@thekavikumar I am not much familiar with react and so I am trying out few changes on the page using chrome dev tools, nothing I have settled on yet. I'll post a ss when m done which would be in a day or two. Thankyou for your patience!

**Comment by thekavikumar** [comment]
Yeah okay bro! Hope you learn something new! 
Happy Hacking
