### ISSUE TITLE
Improve the Web App with any small feature!

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/Gallery#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Manavpreeet** [comment]
Making the top navigation bar more sleek  by adding little styling.

We can enhance the ui of image card with some shadow and little pop up on hover

**Comment by thekavikumar** [comment]
Hmm... Interesting! Try it @Manavpreeet

**Comment by Manavpreeet** [comment]
<img width="1440" alt="Screenshot 2022-10-10 at 10 59 50 PM" src="https://user-images.githubusercontent.com/42695610/194923685-3f71397b-a19f-49fb-9460-e2ac8a963e76.png">

<img width="1440" alt="Screenshot 2022-10-10 at 10 59 42 PM" src="https://user-images.githubusercontent.com/42695610/194923664-73a40021-227f-4f24-b648-b2624d115aa0.png">
