### ISSUE TITLE
Change the dark mode color

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/Gallery#7]
The dark mode color looks not match with dark mode theme. Do change and make a pull request

**Comment by dakshgupta2002** [comment]
Can I work on this issue?

**Comment by thekavikumar** [comment]
Sure

**Comment by noobcoder0702** [comment]
Can I work on this issue

**Comment by thekavikumar** [comment]
Whoever makes the first pull request that will be merged

**Comment by thekavikumar** [comment]
Thanks everyone
