### ISSUE TITLE
Change the title color

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/Gallery#8]
The title Color doesn't look eye-catching. Do change it

**Comment by vishalpatil20** [comment]
Hey @thekavikumar I would like to work on this can you assign me this.

**Comment by mehraankush** [comment]
can i do it that  ..

**Comment by mehraankush** [comment]
can you provide the link plz..

**Comment by noobcoder0702** [comment]
Can I work on this issue

**Comment by thekavikumar** [comment]
> can you provide the link plz..

https://gallery-37066.web.app/

**Comment by mehraankush** [comment]
can it do as it .

**Comment by thekavikumar** [comment]
yeah

**Comment by mehraankush** [comment]
so what do i have to change my gallery or my picture

**Comment by thekavikumar** [comment]
Thanks everyone
